version: '3'
services:
    web:
        container_name: "api_pet_alert"
        env_file:
            - .env_flask
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/flask
        depends_on:
            - psql
        expose:
            - 5000
    psql:
        container_name: "psql_pet_alert"
        image: postgis/postgis
        ports:
          - "5433:5432"
        env_file:
          - .env_psql
        expose:
          - 5433