"""empty message

Revision ID: 10430678fa85
Revises: 96a2554995e7
Create Date: 2021-01-15 05:09:03.619196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10430678fa85'
down_revision = '96a2554995e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'owner', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner', type_='unique')
    # ### end Alembic commands ###
