"""empty message

Revision ID: 9a06ec33adea
Revises: 
Create Date: 2020-10-14 05:58:34.258478

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a06ec33adea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=14), nullable=True),
    sa.Column('f_user', sa.String(length=150), nullable=True),
    sa.Column('g_user', sa.String(length=150), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('firebase_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('age', sa.DECIMAL(), nullable=True),
    sa.Column('weight', sa.DECIMAL(), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('diseases', sa.String(), nullable=True),
    sa.Column('medicates', sa.String(), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('date_registered', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lost_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('date_registered', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_finish', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('pet')
    op.drop_table('owner')
    # ### end Alembic commands ###
